ext {
    group = 'com.tridevmc'
    projectPackage = 'com.tridevmc.architecture'
    projectName = 'architecturecraft'

    useElytraVersionFormat = true
    version = '4'

    compoundVersion = '1.15.0-SNAPSHOT'
    compoundModules = ['all']

    minecraftVersion = "1.21.3"
    minecraftVersionRange = "[1.21.3,1.22)"

    mappingsChannel = "parchment"
    mappingsMinecraftVersion = "1.21"
    mappingsVersion = "2024.07.28"

    neoForgeVersion = "21.3.14-beta"
    neoForgeVersionRange = "[21.3,)"
    loaderVersionRange = "[2,)"
}

if (!ext.early) {
    repositories {
    }

    dependencies {
    }
}
