// See https://github.com/elytra/Skeleton/wiki for what all these values mean

ext {
    group = 'com.tridevmc'
    projectPackage = 'com.tridevmc.architecture'
    projectName = 'architecturecraft'

    useElytraVersionFormat = true
    version = '4'

    compoundVersion = '1.13.0-SNAPSHOT'
    compoundModules = ['all']

    minecraftVersion = "1.20.6"
    minecraftVersionRange = "[1.20.6,1.21)"

    mappingsChannel = "parchment"
    mappingsMinecraftVersion = "1.20.6"
    mappingsVersion = "2024.05.01"

    neoVersion = "20.6.70-beta"
    neoVersionRange = "[20.4,)"
    loaderVersionRange = "[2,)"
}

if (!ext.early) {
    repositories {
    }

    dependencies {
    }
}
